easy_admin:
    site_name: 'Kat'
    formats:
        time: 'h:i:s'
    entities:
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - { property: 'Titre'}
                    - { property: 'SousTitre'}
                    - { property: 'Texte'}
                    - { property: 'Online' }
                    - { property: 'image', type: 'image', base_path: 'imagesArticles' }
                    - { property: 'Date', type: 'date' }
            form:
                fields:
                    - { property: 'Titre'}
                    - { property: 'SousTitre'}
                    - { property: 'Online' }
                    - { property: 'Texte', type: 'fos_ckeditor'}
                    - { property: 'imageFile', type: 'file', base_path: 'imagesArticles' }
        Music:
            class: App\Entity\Music
            list:
                fields:
                    - { property: 'Titre'}
            form:
                fields:
                    - { property: 'Titre'}
                    - { property: 'Embed'}

        Video:
            class: App\Entity\Video
            list:
                fields:
                    - { property: 'Titre'}
            form:
                fields:
                    - { property: 'Titre'}
                    - { property: 'Embed'}
        LiveAgenda:
            class: App\Entity\Event
            list:
                fields:
                    - { property: 'Date', type: 'date'}
                    - { property: 'Horaire' }
                    - { property: 'Lieu'}
                    - { property: 'Titre' }
                    - { property: 'Presentation' }
                    - { property: 'Billeterie',  }
                    - { property: 'image', type: 'image', base_path: 'imagesArticles' }
            form:
                fields:
                    - { property: 'Date', type: 'date'}
                    - { property: 'Horaire', type: 'time' }
                    - { property: 'Lieu'}
                    - { property: 'Titre' }
                    - { property: 'Presentation' }
                    - { property: 'Billeterie', label: 'Liens de la billeterie'}
                    - { property: 'imageFile', type: 'file', base_path: 'imagesArticles' }
                    - { property: 'map', label: 'Embed du lieu sur google maps'}
        Commentaire:
            class: App\Entity\Commentaire
            disabled_actions: ['new']
            list:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'DateTime' }
                    - { property: 'Commentaire' }
                    - { property: 'Valide' }
                    - { property: 'Email' }
            form:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'DateTime' }
                    - { property: 'Commentaire',  type: 'fos_ckeditor' }
                    - { property: 'Valide' }
                    - { property: 'Email' }
        CommentaireArticle:
            class: App\Entity\CommentaireArticle
            disabled_actions: ['new']
            list:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'CreatedAt' }
                    - { property: 'Content' }
                    - { property: 'Valide' }
                    - { property: 'Email' }
            form:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'CreatedAt' }
                    - { property: 'Content',  type: 'fos_ckeditor' }
                    - { property: 'Valide' }
                    - { property: 'Email' }

    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

