easy_admin:
    site_name: 'Kat'
    formats:
        time: 'h:i:s'
    entities:
        News:
            class: App\Entity\Article
            list:
                fields:
                    - { property: 'Titre'}
                    - { property: 'SousTitre'}
                    - { property: 'Texte'}
                    - { property: 'Online',label: 'En ligne'}
                    - { property: 'image', type: 'image', base_path: 'imagesArticles' }
                    - { property: 'Date', type: 'date' }
            form:
                fields:
                    - { property: 'Titre'}
                    - { property: 'SousTitre'}
                    - { property: 'Online',label: 'En ligne'}
                    - { property: 'Texte', type: 'fos_ckeditor'}
                    - { property: 'imageFile', type: 'file', base_path: 'imagesArticles' }
        MusiK:
            class: App\Entity\Music
            list:
                fields:
                    - { property: 'Titre'}
            form:
                fields:
                    - { property: 'Titre'}
                    - { property: 'Embed'}

        Vidéos:
            class: App\Entity\Video
            list:
                fields:
                    - { property: 'Titre'}
            form:
                fields:
                    - { property: 'Titre'}
                    - { property: 'Embed'}
        LiveAgenda:
            class: App\Entity\Event
            list:
                fields:
                    - { property: 'Date', type: 'date'}
                    - { property: 'Horaire' }
                    - { property: 'Lieu'}
                    - { property: 'Titre' }
                    - { property: 'Presentation',label: 'Présentation' }
                    - { property: 'Billeterie',  }
                    - { property: 'image', type: 'image', base_path: 'imagesArticles' }
            form:
                fields:
                    - { property: 'Date', type: 'date'}
                    - { property: 'Horaire', type: 'time' }
                    - { property: 'Lieu'}
                    - { property: 'Titre' }
                    - { property: 'Presentation',label: 'Présentation' }
                    - { property: 'Billeterie', label: 'Liens de la billeterie'}
                    - { property: 'imageFile', type: 'file', base_path: 'imagesArticles' }
                    - { property: 'map', label: 'Embed du lieu sur google maps'}
        LivreDor:
            class: App\Entity\Commentaire
            disabled_actions: ['new']
            list:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'DateTime' }
                    - { property: 'Content',label: 'Commentaire' }
                    - { property: 'Valide' }
                    - { property: 'Email' }
            form:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'DateTime' }
                    - { property: 'Content', type: 'fos_ckeditor' }
                    - { property: 'Valide' }
                    - { property: 'Email' }
        CommentairesArticles:
            class: App\Entity\CommentaireArticle
            disabled_actions: ['new']
            list:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'CreatedAt',label: 'Créé le:' }
                    - { property: 'Content',label: 'Commentaire' }
                    - { property: 'Valide' }
                    - { property: 'Email' }
            form:
                fields:
                    - { property: 'pseudo'}
                    - { property: 'CreatedAt',label: 'Créé le:' }
                    - { property: 'Content',label: 'Commentaire',  type: 'fos_ckeditor' }
                    - { property: 'Valide' }
                    - { property: 'Email' }
        PhotosAccueil:
            class: App\Entity\PhotosAccueil
            disabled_actions: ['delete']
            list:
                fields:
                    - { property: 'id', label: 'N° emplacement'}
                    - { property: 'image', type: 'image', base_path: 'imagesArticles' }
                    - { property: 'titre' }
                    - { property: 'sous_titre' }
            form:
                fields:
                    - { property: 'imageFile', type: 'file', base_path: 'imagesArticles' }
                    - { property: 'titre' }
                    - { property: 'sous_titre' }

    design:
        brand_color: 'rgba(26, 188, 156, 0.85)'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    

